version: '2'
services:
  weeku-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgresql:5432/weeku
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weeku
